export const FILM_LOADED = 'FILM_LOADED';
export const ABOUT_FILM_LOADED = 'ABOUT_FILM_LOADED';
export const CHANGE_SORT = 'CHANGE_SORT';
export const CHANGE_LOAD = 'CHANGE_LOAD';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';

